### ISSUE TITLE
List of stops in a bbox

### ISSUE THREAD

**Issue by pietercolpaert** [derhuerst/hafas-linked-connections-server#1]
Could another endpoint be added to fetch the stops in the configured bbox? That way, we’d be able to visualize the stops on a map, as well as snap it to OSM to calculate transfers between stops automatically.

An example of what we need: https://graph.irail.be/sncb/stops

`@id`, name, longitude and latitude would be great to be able to visualize the stop!

**Comment by derhuerst** [comment]
We can build this using [`hafas.nearby()`](https://github.com/public-transport/hafas-client/blob/4/docs/nearby.md).
